images:
  machine-controller-manager: image-repository:image-tag
  machine-controller-manager-provider-azure: image-repository:image-tag

replicas: 1

podAnnotations: {}

podLabels: {}

providerName: provider-foo

# injected by generic worker actuator
genericTokenKubeconfigSecretName: generic-token-kubeconfig

namespace:
  uid: uuid-of-namespace

metricsPort: 10258
metricsPortAzure: 10259

vpa:
  enabled: true
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    mcm:
      maxAllowed:
        cpu: 2
        memory: 5G
    mcmProviderAzure:
      maxAllowed:
        cpu: 2
        memory: 5G

resources:
  mcm:
    requests:
      cpu: 31m
      memory: 70Mi
    limits:
      memory: 2Gi
  mcmProviderAzure:
    requests:
      cpu: 30m
      memory: 64Mi
