replicas: 1
podAnnotations: {}
images:
  remedy-controller-azure: image-repository:image-tag
resources:
  requests:
    cpu: 50m
    memory: 72M 

manager:
  metricsPort: 10258
targetManager:
  metricsPort: 10259

controllers:
  publicipaddress:
    concurrentSyncs: 5
  virtualmachine:
    concurrentSyncs: 5
  service:
    concurrentSyncs: 5
  node:
    concurrentSyncs: 5

disableControllers: []
targetDisableControllers: []

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  azure:
    orphanedPublicIPRemedy:
      requeueInterval: 1m
      syncPeriod: 10h
      deletionGracePeriod: 5m
      maxGetAttempts: 5
      maxCleanAttempts: 5
    failedVMRemedy:
      requeueInterval: 1m
      syncPeriod: 2h
      maxGetAttempts: 5
      maxReapplyAttempts: 5

# TODO(rfranzke): Remove this field after August 2024.
gep19Monitoring: false

useWorkloadIdentity: false
