images:
- name: terraformer
  sourceRepository: github.com/gardener/terraformer
  repository: eu.gcr.io/gardener-project/gardener/terraformer-azure
  tag: "v2.18.1"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'

- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.20.15"
  targetVersion: "1.20.x"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.21.12"
  targetVersion: "1.21.x"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-controller-manager
  sourceRepository: github.com/gardener/cloud-provider-azure
  repository: eu.gcr.io/gardener-project/kubernetes/cloud-provider-azure
  tag: "v1.22.17"
  targetVersion: "1.22.x"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes-sigs/cloud-provider-azure
  repository: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager
  tag: "v1.23.25"
  targetVersion: "1.23.x"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes-sigs/cloud-provider-azure
  repository: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager
  tag: "v1.24.12"
  targetVersion: "1.24.x"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes-sigs/cloud-provider-azure
  repository: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager
  tag: "v1.25.6"
  targetVersion: "1.25.x"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-controller-manager
  sourceRepository: github.com/kubernetes-sigs/cloud-provider-azure
  repository: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager
  tag: "v1.26.2"
  targetVersion: ">= 1.26"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'

- name: cloud-node-manager
  sourceRepository: github.com/kubernetes-sigs/cloud-provider-azure
  repository: mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager
  tag: "v1.23.25"
  targetVersion: "< 1.24"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-node-manager
  sourceRepository: github.com/kubernetes-sigs/cloud-provider-azure
  repository: mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager
  tag: "v1.24.12"
  targetVersion: "1.24.x"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-node-manager
  sourceRepository: github.com/kubernetes-sigs/cloud-provider-azure
  repository: mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager
  tag: "v1.25.6"
  targetVersion: "1.25.x"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: cloud-node-manager
  sourceRepository: github.com/kubernetes-sigs/cloud-provider-azure
  repository: mcr.microsoft.com/oss/kubernetes/azure-cloud-node-manager
  tag: "v1.26.2"
  targetVersion: ">= 1.26"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'

- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.48.1"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: machine-controller-manager-provider-azure
  sourceRepository: github.com/gardener/machine-controller-manager-provider-azure
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager-provider-azure
  tag: "v0.9.0"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'

- name: csi-driver-disk
  sourceRepository: github.com/kubernetes-sigs/azuredisk-csi-driver
  repository: mcr.microsoft.com/k8s/csi/azuredisk-csi
  tag: "v1.25.0"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'end-user'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-driver-file
  sourceRepository: github.com/kubernetes-sigs/azurefile-csi-driver
  repository: mcr.microsoft.com/k8s/csi/azurefile-csi
  tag: "v1.21.0"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'end-user'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-provisioner
  sourceRepository: github.com/kubernetes-csi/external-provisioner
  repository: registry.k8s.io/sig-storage/csi-provisioner
  tag: "v3.2.0"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'private'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'low'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-attacher
  sourceRepository: github.com/kubernetes-csi/external-attacher
  repository: registry.k8s.io/sig-storage/csi-attacher
  tag: "v3.4.0"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'private'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'low'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-snapshotter
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: registry.k8s.io/sig-storage/csi-snapshotter
  tag: "v4.2.1"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'private'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'low'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-snapshot-controller
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: registry.k8s.io/sig-storage/snapshot-controller
  tag: "v4.2.1"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'private'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'low'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-snapshot-validation-webhook
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: registry.k8s.io/sig-storage/snapshot-validation-webhook
  tag: "v4.2.1"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'private'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'low'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-resizer
  sourceRepository: github.com/kubernetes-csi/external-resizer
  repository: registry.k8s.io/sig-storage/csi-resizer
  tag: "v1.5.0"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'private'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'low'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-node-driver-registrar
  sourceRepository: github.com/kubernetes-csi/node-driver-registrar
  repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
  tag: "v2.5.1"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'private'
      authentication_enforced: false
      user_interaction: 'end-user'
      confidentiality_requirement: 'low'
      integrity_requirement: 'high'
      availability_requirement: 'low'
- name: csi-liveness-probe
  sourceRepository: github.com/kubernetes-csi/livenessprobe
  repository: registry.k8s.io/sig-storage/livenessprobe
  tag: "v2.7.0"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'private'
      authentication_enforced: false
      user_interaction: 'end-user'
      confidentiality_requirement: 'low'
      integrity_requirement: 'high'
      availability_requirement: 'low'

- name: remedy-controller-azure
  sourceRepository: github.com/gardener/remedy-controller
  repository: eu.gcr.io/gardener-project/gardener/remedy-controller/remedy-controller-azure
  tag: "v0.10.0"
  labels:
  - name: 'gardener.cloud/cve-categorisation'
    value:
      network_exposure: 'protected'
      authentication_enforced: false
      user_interaction: 'gardener-operator'
      confidentiality_requirement: 'high'
      integrity_requirement: 'high'
      availability_requirement: 'low'
