name: AI-assisted PR Summary
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  summary:
    name: PR Summary
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: write
    steps:
      - uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
        with:
          aicore-service-key: ${{ secrets.AICORE_SERVICE_KEY }}
          model: anthropic--claude-4-sonnet
          exclude-files: package-lock.json
          display-mode: comment
          previous-results: delete
