apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-logging-config
  namespace: garden
  labels:
    extensions.gardener.cloud/configuration: logging
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                parser
        Match               kubernetes.*cloud-controller-manager*azure-cloud-controller-manager*
        Key_Name            log
        Parser              kubeapiserverParser
        Reserve_Data        True

    [FILTER]
        Name                parser
        Match               kubernetes.*machine-controller-manager*azure*
        Key_Name            log
        Parser              kubeapiserverParser
        Reserve_Data        True

    [FILTER]
        Name                parser
        Match               kubernetes.*csi-driver-controller*azure-csi*
        Key_Name            log
        Parser              kubeapiserverParser
        Reserve_Data        True

    [FILTER]
        Name                parser
        Match               kubernetes.*csi-snapshot*azure-csi*
        Key_Name            log
        Parser              kubeapiserverParser
        Reserve_Data        True

    [FILTER]
        Name                modify
        Match               kubernetes.*
        Condition           Key_value_matches tag ^kubernetes\.var\.log\.containers\.(cloud-controller-manager-.+?_.+?_azure-cloud-controller-manager|csi-driver-controller-.+?_.+?_azure-csi)
        Add                 __gardener_multitenant_id__ operator;user

    [FILTER]
        Name                modify
        Match               kubernetes.*
        Condition           Key_value_matches tag ^kubernetes\.var\.log\.containers\.machine-controller-manager-.+?_.+?_(machine-controller-manager-provider-azure|azure-machine-controller-manager)
        Add                 __gardener_multitenant_id__ operator;user
